def includeme(config):
    config.add_static_view('static', 'static', cache_max_age=3600)
    config.add_route('logintype', '/')
    config.add_route('adminlogin', '/adminlogin')
    config.add_route('list_block','/blocks')
    config.add_route('listhouseowner','/lhpg')
    config.add_route('addhouseownerpg','/hpg')
    config.add_route('viewhouseowner','/lhpg/{id}')
    config.add_route('editthouseowner','/lhpg/{id}/edit')
    config.add_route('deletehouseowner','/lhpg/{id}/delete')
    config.add_route('adminaddtenantpg','/addtenant/{id}')
    config.add_route('admindeletetenant','/deletetenant/{id}')
    config.add_route('searchtype','/search')
    config.add_route('houseownerlogin','/login')
    config.add_route('listtenantpg','/ltpg')
    config.add_route('addtenantpg','/tpg')
    config.add_route('viewtenantpg', '/ltpg/{id}')
    config.add_route('edittenantpg','/ltpg/{id}/edit')
    config.add_route('deletetenantpg','/ltpg/{id}/delete')
